name: Chacha20-ietf
type: stream
checksumsmall: 9dfc28222edf92880d56152f1c51c0c56a8aff3338503ab3727b6f05d85f4b2c
checksumbig: aa60fcc9a95ee7b4fbf47d166ad1a56bc1a288b309c70a2be10455db649dcc53
implementations:
    - name: amd64/ref
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
    - name: amd64/mmx
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
    - name: amd64/avx
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - avx
    - name: amd64/avx2
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems: # FIXME
              - Linux
              - Darwin
          required_flags:
              - avx2

