name: Chacha12
type: stream
checksumsmall: 28a7bcf9ec6ed8a3a0870972f1e3f6ee652f8e8eaba83756eebb012f57f2565b
checksumbig: e4193652aacbb2ff30e062d7b9ce0721dbc3653451eed858c0c621872310ab90
implementations:
    - name: amd64/ref
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
    - name: amd64/mmx
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
    - name: amd64/avx
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - avx
    - name: amd64/avx2
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems: # FIXME
              - Linux
              - Darwin
          required_flags:
              - avx2

